// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReplicaUpcall.proto

package org.apache.hadoop.hdfs.server.namenode.spec;

public final class ReplicaUpcall {
  private ReplicaUpcall() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .hadoop.hdfs.Request.Operation op = 1;
    /**
     * <code>required .hadoop.hdfs.Request.Operation op = 1;</code>
     */
    boolean hasOp();
    /**
     * <code>required .hadoop.hdfs.Request.Operation op = 1;</code>
     */
    org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation getOp();

    // optional string user = 2;
    /**
     * <code>optional string user = 2;</code>
     */
    boolean hasUser();
    /**
     * <code>optional string user = 2;</code>
     */
    java.lang.String getUser();
    /**
     * <code>optional string user = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    // optional string src = 3;
    /**
     * <code>optional string src = 3;</code>
     */
    boolean hasSrc();
    /**
     * <code>optional string src = 3;</code>
     */
    java.lang.String getSrc();
    /**
     * <code>optional string src = 3;</code>
     */
    com.google.protobuf.ByteString
        getSrcBytes();

    // optional string dst = 4;
    /**
     * <code>optional string dst = 4;</code>
     */
    boolean hasDst();
    /**
     * <code>optional string dst = 4;</code>
     */
    java.lang.String getDst();
    /**
     * <code>optional string dst = 4;</code>
     */
    com.google.protobuf.ByteString
        getDstBytes();

    // optional bool recursive = 5;
    /**
     * <code>optional bool recursive = 5;</code>
     */
    boolean hasRecursive();
    /**
     * <code>optional bool recursive = 5;</code>
     */
    boolean getRecursive();

    // optional int32 masked = 6;
    /**
     * <code>optional int32 masked = 6;</code>
     */
    boolean hasMasked();
    /**
     * <code>optional int32 masked = 6;</code>
     */
    int getMasked();

    // optional bool createparent = 7;
    /**
     * <code>optional bool createparent = 7;</code>
     */
    boolean hasCreateparent();
    /**
     * <code>optional bool createparent = 7;</code>
     */
    boolean getCreateparent();
  }
  /**
   * Protobuf type {@code hadoop.hdfs.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation value = org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                op_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              user_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              src_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dst_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              recursive_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              masked_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              createparent_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.class, org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code hadoop.hdfs.Request.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MKDIR = 1;</code>
       */
      MKDIR(0, 1),
      /**
       * <code>RM = 2;</code>
       */
      RM(1, 2),
      /**
       * <code>LS = 3;</code>
       */
      LS(2, 3),
      ;

      /**
       * <code>MKDIR = 1;</code>
       */
      public static final int MKDIR_VALUE = 1;
      /**
       * <code>RM = 2;</code>
       */
      public static final int RM_VALUE = 2;
      /**
       * <code>LS = 3;</code>
       */
      public static final int LS_VALUE = 3;


      public final int getNumber() { return value; }

      public static Operation valueOf(int value) {
        switch (value) {
          case 1: return MKDIR;
          case 2: return RM;
          case 3: return LS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Operation(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:hadoop.hdfs.Request.Operation)
    }

    private int bitField0_;
    // required .hadoop.hdfs.Request.Operation op = 1;
    public static final int OP_FIELD_NUMBER = 1;
    private org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation op_;
    /**
     * <code>required .hadoop.hdfs.Request.Operation op = 1;</code>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .hadoop.hdfs.Request.Operation op = 1;</code>
     */
    public org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation getOp() {
      return op_;
    }

    // optional string user = 2;
    public static final int USER_FIELD_NUMBER = 2;
    private java.lang.Object user_;
    /**
     * <code>optional string user = 2;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string user = 2;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          user_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string src = 3;
    public static final int SRC_FIELD_NUMBER = 3;
    private java.lang.Object src_;
    /**
     * <code>optional string src = 3;</code>
     */
    public boolean hasSrc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string src = 3;</code>
     */
    public java.lang.String getSrc() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          src_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string src = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSrcBytes() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        src_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string dst = 4;
    public static final int DST_FIELD_NUMBER = 4;
    private java.lang.Object dst_;
    /**
     * <code>optional string dst = 4;</code>
     */
    public boolean hasDst() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string dst = 4;</code>
     */
    public java.lang.String getDst() {
      java.lang.Object ref = dst_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dst_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dst = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDstBytes() {
      java.lang.Object ref = dst_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool recursive = 5;
    public static final int RECURSIVE_FIELD_NUMBER = 5;
    private boolean recursive_;
    /**
     * <code>optional bool recursive = 5;</code>
     */
    public boolean hasRecursive() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool recursive = 5;</code>
     */
    public boolean getRecursive() {
      return recursive_;
    }

    // optional int32 masked = 6;
    public static final int MASKED_FIELD_NUMBER = 6;
    private int masked_;
    /**
     * <code>optional int32 masked = 6;</code>
     */
    public boolean hasMasked() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 masked = 6;</code>
     */
    public int getMasked() {
      return masked_;
    }

    // optional bool createparent = 7;
    public static final int CREATEPARENT_FIELD_NUMBER = 7;
    private boolean createparent_;
    /**
     * <code>optional bool createparent = 7;</code>
     */
    public boolean hasCreateparent() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool createparent = 7;</code>
     */
    public boolean getCreateparent() {
      return createparent_;
    }

    private void initFields() {
      op_ = org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation.MKDIR;
      user_ = "";
      src_ = "";
      dst_ = "";
      recursive_ = false;
      masked_ = 0;
      createparent_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, op_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSrcBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDstBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, recursive_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, masked_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, createparent_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, op_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSrcBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDstBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, recursive_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, masked_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, createparent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request)) {
        return super.equals(obj);
      }
      org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request other = (org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request) obj;

      boolean result = true;
      result = result && (hasOp() == other.hasOp());
      if (hasOp()) {
        result = result &&
            (getOp() == other.getOp());
      }
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && (hasSrc() == other.hasSrc());
      if (hasSrc()) {
        result = result && getSrc()
            .equals(other.getSrc());
      }
      result = result && (hasDst() == other.hasDst());
      if (hasDst()) {
        result = result && getDst()
            .equals(other.getDst());
      }
      result = result && (hasRecursive() == other.hasRecursive());
      if (hasRecursive()) {
        result = result && (getRecursive()
            == other.getRecursive());
      }
      result = result && (hasMasked() == other.hasMasked());
      if (hasMasked()) {
        result = result && (getMasked()
            == other.getMasked());
      }
      result = result && (hasCreateparent() == other.hasCreateparent());
      if (hasCreateparent()) {
        result = result && (getCreateparent()
            == other.getCreateparent());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasOp()) {
        hash = (37 * hash) + OP_FIELD_NUMBER;
        hash = (53 * hash) + hashEnum(getOp());
      }
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasSrc()) {
        hash = (37 * hash) + SRC_FIELD_NUMBER;
        hash = (53 * hash) + getSrc().hashCode();
      }
      if (hasDst()) {
        hash = (37 * hash) + DST_FIELD_NUMBER;
        hash = (53 * hash) + getDst().hashCode();
      }
      if (hasRecursive()) {
        hash = (37 * hash) + RECURSIVE_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getRecursive());
      }
      if (hasMasked()) {
        hash = (37 * hash) + MASKED_FIELD_NUMBER;
        hash = (53 * hash) + getMasked();
      }
      if (hasCreateparent()) {
        hash = (37 * hash) + CREATEPARENT_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getCreateparent());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hadoop.hdfs.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.class, org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Builder.class);
      }

      // Construct using org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        op_ = org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation.MKDIR;
        bitField0_ = (bitField0_ & ~0x00000001);
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        src_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dst_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        recursive_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        masked_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        createparent_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Request_descriptor;
      }

      public org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request getDefaultInstanceForType() {
        return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.getDefaultInstance();
      }

      public org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request build() {
        org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request buildPartial() {
        org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request result = new org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.op_ = op_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.src_ = src_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dst_ = dst_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.recursive_ = recursive_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.masked_ = masked_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.createparent_ = createparent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request) {
          return mergeFrom((org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request other) {
        if (other == org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.getDefaultInstance()) return this;
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        if (other.hasUser()) {
          bitField0_ |= 0x00000002;
          user_ = other.user_;
          onChanged();
        }
        if (other.hasSrc()) {
          bitField0_ |= 0x00000004;
          src_ = other.src_;
          onChanged();
        }
        if (other.hasDst()) {
          bitField0_ |= 0x00000008;
          dst_ = other.dst_;
          onChanged();
        }
        if (other.hasRecursive()) {
          setRecursive(other.getRecursive());
        }
        if (other.hasMasked()) {
          setMasked(other.getMasked());
        }
        if (other.hasCreateparent()) {
          setCreateparent(other.getCreateparent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .hadoop.hdfs.Request.Operation op = 1;
      private org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation op_ = org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation.MKDIR;
      /**
       * <code>required .hadoop.hdfs.Request.Operation op = 1;</code>
       */
      public boolean hasOp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .hadoop.hdfs.Request.Operation op = 1;</code>
       */
      public org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation getOp() {
        return op_;
      }
      /**
       * <code>required .hadoop.hdfs.Request.Operation op = 1;</code>
       */
      public Builder setOp(org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .hadoop.hdfs.Request.Operation op = 1;</code>
       */
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        op_ = org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Request.Operation.MKDIR;
        onChanged();
        return this;
      }

      // optional string user = 2;
      private java.lang.Object user_ = "";
      /**
       * <code>optional string user = 2;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000002);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        user_ = value;
        onChanged();
        return this;
      }

      // optional string src = 3;
      private java.lang.Object src_ = "";
      /**
       * <code>optional string src = 3;</code>
       */
      public boolean hasSrc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public java.lang.String getSrc() {
        java.lang.Object ref = src_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          src_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSrcBytes() {
        java.lang.Object ref = src_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          src_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public Builder setSrc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        src_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public Builder clearSrc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        src_ = getDefaultInstance().getSrc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string src = 3;</code>
       */
      public Builder setSrcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        src_ = value;
        onChanged();
        return this;
      }

      // optional string dst = 4;
      private java.lang.Object dst_ = "";
      /**
       * <code>optional string dst = 4;</code>
       */
      public boolean hasDst() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string dst = 4;</code>
       */
      public java.lang.String getDst() {
        java.lang.Object ref = dst_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dst_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dst = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDstBytes() {
        java.lang.Object ref = dst_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dst_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dst = 4;</code>
       */
      public Builder setDst(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dst = 4;</code>
       */
      public Builder clearDst() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dst_ = getDefaultInstance().getDst();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dst = 4;</code>
       */
      public Builder setDstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dst_ = value;
        onChanged();
        return this;
      }

      // optional bool recursive = 5;
      private boolean recursive_ ;
      /**
       * <code>optional bool recursive = 5;</code>
       */
      public boolean hasRecursive() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool recursive = 5;</code>
       */
      public boolean getRecursive() {
        return recursive_;
      }
      /**
       * <code>optional bool recursive = 5;</code>
       */
      public Builder setRecursive(boolean value) {
        bitField0_ |= 0x00000010;
        recursive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool recursive = 5;</code>
       */
      public Builder clearRecursive() {
        bitField0_ = (bitField0_ & ~0x00000010);
        recursive_ = false;
        onChanged();
        return this;
      }

      // optional int32 masked = 6;
      private int masked_ ;
      /**
       * <code>optional int32 masked = 6;</code>
       */
      public boolean hasMasked() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 masked = 6;</code>
       */
      public int getMasked() {
        return masked_;
      }
      /**
       * <code>optional int32 masked = 6;</code>
       */
      public Builder setMasked(int value) {
        bitField0_ |= 0x00000020;
        masked_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 masked = 6;</code>
       */
      public Builder clearMasked() {
        bitField0_ = (bitField0_ & ~0x00000020);
        masked_ = 0;
        onChanged();
        return this;
      }

      // optional bool createparent = 7;
      private boolean createparent_ ;
      /**
       * <code>optional bool createparent = 7;</code>
       */
      public boolean hasCreateparent() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool createparent = 7;</code>
       */
      public boolean getCreateparent() {
        return createparent_;
      }
      /**
       * <code>optional bool createparent = 7;</code>
       */
      public Builder setCreateparent(boolean value) {
        bitField0_ |= 0x00000040;
        createparent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool createparent = 7;</code>
       */
      public Builder clearCreateparent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        createparent_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hadoop.hdfs.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hadoop.hdfs.Request)
  }

  public interface ReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 exception = 1;
    /**
     * <code>optional int32 exception = 1;</code>
     */
    boolean hasException();
    /**
     * <code>optional int32 exception = 1;</code>
     */
    int getException();

    // optional bool success = 2;
    /**
     * <code>optional bool success = 2;</code>
     */
    boolean hasSuccess();
    /**
     * <code>optional bool success = 2;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code hadoop.hdfs.Reply}
   */
  public static final class Reply extends
      com.google.protobuf.GeneratedMessage
      implements ReplyOrBuilder {
    // Use Reply.newBuilder() to construct.
    private Reply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Reply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Reply defaultInstance;
    public static Reply getDefaultInstance() {
      return defaultInstance;
    }

    public Reply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              exception_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply.class, org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply.Builder.class);
    }

    public static com.google.protobuf.Parser<Reply> PARSER =
        new com.google.protobuf.AbstractParser<Reply>() {
      public Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Reply> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 exception = 1;
    public static final int EXCEPTION_FIELD_NUMBER = 1;
    private int exception_;
    /**
     * <code>optional int32 exception = 1;</code>
     */
    public boolean hasException() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 exception = 1;</code>
     */
    public int getException() {
      return exception_;
    }

    // optional bool success = 2;
    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <code>optional bool success = 2;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool success = 2;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private void initFields() {
      exception_ = 0;
      success_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, exception_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, success_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, exception_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply)) {
        return super.equals(obj);
      }
      org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply other = (org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply) obj;

      boolean result = true;
      result = result && (hasException() == other.hasException());
      if (hasException()) {
        result = result && (getException()
            == other.getException());
      }
      result = result && (hasSuccess() == other.hasSuccess());
      if (hasSuccess()) {
        result = result && (getSuccess()
            == other.getSuccess());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasException()) {
        hash = (37 * hash) + EXCEPTION_FIELD_NUMBER;
        hash = (53 * hash) + getException();
      }
      if (hasSuccess()) {
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getSuccess());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hadoop.hdfs.Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply.class, org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply.Builder.class);
      }

      // Construct using org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        exception_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.internal_static_hadoop_hdfs_Reply_descriptor;
      }

      public org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply getDefaultInstanceForType() {
        return org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply.getDefaultInstance();
      }

      public org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply build() {
        org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply buildPartial() {
        org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply result = new org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exception_ = exception_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.success_ = success_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply) {
          return mergeFrom((org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply other) {
        if (other == org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply.getDefaultInstance()) return this;
        if (other.hasException()) {
          setException(other.getException());
        }
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.hadoop.hdfs.server.namenode.spec.ReplicaUpcall.Reply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 exception = 1;
      private int exception_ ;
      /**
       * <code>optional int32 exception = 1;</code>
       */
      public boolean hasException() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 exception = 1;</code>
       */
      public int getException() {
        return exception_;
      }
      /**
       * <code>optional int32 exception = 1;</code>
       */
      public Builder setException(int value) {
        bitField0_ |= 0x00000001;
        exception_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exception = 1;</code>
       */
      public Builder clearException() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exception_ = 0;
        onChanged();
        return this;
      }

      // optional bool success = 2;
      private boolean success_ ;
      /**
       * <code>optional bool success = 2;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool success = 2;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 2;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000002;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 2;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hadoop.hdfs.Reply)
    }

    static {
      defaultInstance = new Reply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hadoop.hdfs.Reply)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hadoop_hdfs_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hadoop_hdfs_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hadoop_hdfs_Reply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hadoop_hdfs_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ReplicaUpcall.proto\022\013hadoop.hdfs\"\276\001\n\007R" +
      "equest\022*\n\002op\030\001 \002(\0162\036.hadoop.hdfs.Request" +
      ".Operation\022\014\n\004user\030\002 \001(\t\022\013\n\003src\030\003 \001(\t\022\013\n" +
      "\003dst\030\004 \001(\t\022\021\n\trecursive\030\005 \001(\010\022\016\n\006masked\030" +
      "\006 \001(\005\022\024\n\014createparent\030\007 \001(\010\"&\n\tOperation" +
      "\022\t\n\005MKDIR\020\001\022\006\n\002RM\020\002\022\006\n\002LS\020\003\"+\n\005Reply\022\021\n\t" +
      "exception\030\001 \001(\005\022\017\n\007success\030\002 \001(\010B?\n+org." +
      "apache.hadoop.hdfs.server.namenode.specB" +
      "\rReplicaUpcall\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hadoop_hdfs_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hadoop_hdfs_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hadoop_hdfs_Request_descriptor,
              new java.lang.String[] { "Op", "User", "Src", "Dst", "Recursive", "Masked", "Createparent", });
          internal_static_hadoop_hdfs_Reply_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_hadoop_hdfs_Reply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hadoop_hdfs_Reply_descriptor,
              new java.lang.String[] { "Exception", "Success", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
